### ISSUE TITLE
这个可以支持Unicode吗

### ISSUE THREAD

**Issue by suraxiuxiu** [fenghou1st/MangaMeeya-ChineseTranslation#1]
感觉这个软件最大的遗憾就是这个了

**Comment by fenghou1st** [comment]
确实不能. 可以用同作者的另一个支持 Unicode 的软件 MangaMeeya CE, 虽然功能少一些.

**Comment by fenghou1st** [comment]
网上找了一圈, 发现有人写了一个包装器, 可以支持打开 Unicode 名称的文件了: https://github.com/kaperx/altermeeya

**Comment by suraxiuxiu** [comment]
altermeeya用过 不太理想 仅支持在Windows文件夹里右键打开图片或者压缩包  进到mangameeya里边后 返回浏览图库还是不识别

**Comment by jarupxx** [comment]
将此资源 (https://github.com/jarupxx/MangaMeeya) 与 RisohEditor (https://github.com/katahiromz/RisohEditor) 集成。 支持Unicode码。
